### ISSUE TITLE
Clarification of pipeline

### ISSUE THREAD

**Issue by MySelvan** [abhisheknrl/myeloid_lymphoid_CH#1]
Hi,

I recently came across your paper "Distinction of lymphoid and myeloid clonal hematopoiesis" and found it very interesting.

I would like identify L/M-CHIP carriers in our cohort.
In the manuscript, regarding the pipeline for detection of CHIP from WES, it is stated "remaining variants were manually curated to filter out potential artifacts"
Could you please elaborate on what kind of potential artifacts were observed and what criteria was used for manual curation.

**Comment by abhisheknrl** [comment]
Hello,

The manual curation was mainly focussed on the quality of variants. We inspected the variants in IGV to check that the variants are reliable. For example, base quality, alignment quality, position of variant alleles in the reads, etc. I have included some of the IGV screenshots for the variants that failed manual curation.
For inclusion, the majority of the reads supporting the variant allele should have base quality >= 30, alignment quality == max possible for read length, position >= 5 from the end of the reads.

![Example_of_manual_curation](https://user-images.githubusercontent.com/11738632/173544869-fb629e2b-1308-4c69-accd-ecc9ae01a363.png)
